// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef PROTOBUF_message_2eproto__INCLUDED
#define PROTOBUF_message_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003002 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
class Message;
class MessageDefaultTypeInternal;
extern MessageDefaultTypeInternal _Message_default_instance_;
class Message_Frame;
class Message_FrameDefaultTypeInternal;
extern Message_FrameDefaultTypeInternal _Message_Frame_default_instance_;
class Message_Frame_Point;
class Message_Frame_PointDefaultTypeInternal;
extern Message_Frame_PointDefaultTypeInternal _Message_Frame_Point_default_instance_;

namespace protobuf_message_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_message_2eproto

// ===================================================================

class Message_Frame_Point : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Message.Frame.Point) */ {
 public:
  Message_Frame_Point();
  virtual ~Message_Frame_Point();

  Message_Frame_Point(const Message_Frame_Point& from);

  inline Message_Frame_Point& operator=(const Message_Frame_Point& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Message_Frame_Point& default_instance();

  static inline const Message_Frame_Point* internal_default_instance() {
    return reinterpret_cast<const Message_Frame_Point*>(
               &_Message_Frame_Point_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Message_Frame_Point* other);

  // implements Message ----------------------------------------------

  inline Message_Frame_Point* New() const PROTOBUF_FINAL { return New(NULL); }

  Message_Frame_Point* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Message_Frame_Point& from);
  void MergeFrom(const Message_Frame_Point& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Message_Frame_Point* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // float y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // float z = 3;
  void clear_z();
  static const int kZFieldNumber = 3;
  float z() const;
  void set_z(float value);

  // uint32 r = 4;
  void clear_r();
  static const int kRFieldNumber = 4;
  ::google::protobuf::uint32 r() const;
  void set_r(::google::protobuf::uint32 value);

  // uint32 g = 5;
  void clear_g();
  static const int kGFieldNumber = 5;
  ::google::protobuf::uint32 g() const;
  void set_g(::google::protobuf::uint32 value);

  // uint32 b = 6;
  void clear_b();
  static const int kBFieldNumber = 6;
  ::google::protobuf::uint32 b() const;
  void set_b(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:Message.Frame.Point)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  float x_;
  float y_;
  float z_;
  ::google::protobuf::uint32 r_;
  ::google::protobuf::uint32 g_;
  ::google::protobuf::uint32 b_;
  mutable int _cached_size_;
  friend struct protobuf_message_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Message_Frame : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Message.Frame) */ {
 public:
  Message_Frame();
  virtual ~Message_Frame();

  Message_Frame(const Message_Frame& from);

  inline Message_Frame& operator=(const Message_Frame& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Message_Frame& default_instance();

  static inline const Message_Frame* internal_default_instance() {
    return reinterpret_cast<const Message_Frame*>(
               &_Message_Frame_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(Message_Frame* other);

  // implements Message ----------------------------------------------

  inline Message_Frame* New() const PROTOBUF_FINAL { return New(NULL); }

  Message_Frame* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Message_Frame& from);
  void MergeFrom(const Message_Frame& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Message_Frame* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef Message_Frame_Point Point;

  // accessors -------------------------------------------------------

  // repeated .Message.Frame.Point points = 1;
  int points_size() const;
  void clear_points();
  static const int kPointsFieldNumber = 1;
  const ::Message_Frame_Point& points(int index) const;
  ::Message_Frame_Point* mutable_points(int index);
  ::Message_Frame_Point* add_points();
  ::google::protobuf::RepeatedPtrField< ::Message_Frame_Point >*
      mutable_points();
  const ::google::protobuf::RepeatedPtrField< ::Message_Frame_Point >&
      points() const;

  // float timestamp = 2;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 2;
  float timestamp() const;
  void set_timestamp(float value);

  // @@protoc_insertion_point(class_scope:Message.Frame)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::Message_Frame_Point > points_;
  float timestamp_;
  mutable int _cached_size_;
  friend struct protobuf_message_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Message : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Message) */ {
 public:
  Message();
  virtual ~Message();

  Message(const Message& from);

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Message& default_instance();

  static inline const Message* internal_default_instance() {
    return reinterpret_cast<const Message*>(
               &_Message_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(Message* other);

  // implements Message ----------------------------------------------

  inline Message* New() const PROTOBUF_FINAL { return New(NULL); }

  Message* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Message& from);
  void MergeFrom(const Message& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Message* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef Message_Frame Frame;

  // accessors -------------------------------------------------------

  // repeated .Message.Frame frames = 1;
  int frames_size() const;
  void clear_frames();
  static const int kFramesFieldNumber = 1;
  const ::Message_Frame& frames(int index) const;
  ::Message_Frame* mutable_frames(int index);
  ::Message_Frame* add_frames();
  ::google::protobuf::RepeatedPtrField< ::Message_Frame >*
      mutable_frames();
  const ::google::protobuf::RepeatedPtrField< ::Message_Frame >&
      frames() const;

  // @@protoc_insertion_point(class_scope:Message)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::Message_Frame > frames_;
  mutable int _cached_size_;
  friend struct protobuf_message_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Message_Frame_Point

// float x = 1;
inline void Message_Frame_Point::clear_x() {
  x_ = 0;
}
inline float Message_Frame_Point::x() const {
  // @@protoc_insertion_point(field_get:Message.Frame.Point.x)
  return x_;
}
inline void Message_Frame_Point::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:Message.Frame.Point.x)
}

// float y = 2;
inline void Message_Frame_Point::clear_y() {
  y_ = 0;
}
inline float Message_Frame_Point::y() const {
  // @@protoc_insertion_point(field_get:Message.Frame.Point.y)
  return y_;
}
inline void Message_Frame_Point::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:Message.Frame.Point.y)
}

// float z = 3;
inline void Message_Frame_Point::clear_z() {
  z_ = 0;
}
inline float Message_Frame_Point::z() const {
  // @@protoc_insertion_point(field_get:Message.Frame.Point.z)
  return z_;
}
inline void Message_Frame_Point::set_z(float value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:Message.Frame.Point.z)
}

// uint32 r = 4;
inline void Message_Frame_Point::clear_r() {
  r_ = 0u;
}
inline ::google::protobuf::uint32 Message_Frame_Point::r() const {
  // @@protoc_insertion_point(field_get:Message.Frame.Point.r)
  return r_;
}
inline void Message_Frame_Point::set_r(::google::protobuf::uint32 value) {
  
  r_ = value;
  // @@protoc_insertion_point(field_set:Message.Frame.Point.r)
}

// uint32 g = 5;
inline void Message_Frame_Point::clear_g() {
  g_ = 0u;
}
inline ::google::protobuf::uint32 Message_Frame_Point::g() const {
  // @@protoc_insertion_point(field_get:Message.Frame.Point.g)
  return g_;
}
inline void Message_Frame_Point::set_g(::google::protobuf::uint32 value) {
  
  g_ = value;
  // @@protoc_insertion_point(field_set:Message.Frame.Point.g)
}

// uint32 b = 6;
inline void Message_Frame_Point::clear_b() {
  b_ = 0u;
}
inline ::google::protobuf::uint32 Message_Frame_Point::b() const {
  // @@protoc_insertion_point(field_get:Message.Frame.Point.b)
  return b_;
}
inline void Message_Frame_Point::set_b(::google::protobuf::uint32 value) {
  
  b_ = value;
  // @@protoc_insertion_point(field_set:Message.Frame.Point.b)
}

// -------------------------------------------------------------------

// Message_Frame

// repeated .Message.Frame.Point points = 1;
inline int Message_Frame::points_size() const {
  return points_.size();
}
inline void Message_Frame::clear_points() {
  points_.Clear();
}
inline const ::Message_Frame_Point& Message_Frame::points(int index) const {
  // @@protoc_insertion_point(field_get:Message.Frame.points)
  return points_.Get(index);
}
inline ::Message_Frame_Point* Message_Frame::mutable_points(int index) {
  // @@protoc_insertion_point(field_mutable:Message.Frame.points)
  return points_.Mutable(index);
}
inline ::Message_Frame_Point* Message_Frame::add_points() {
  // @@protoc_insertion_point(field_add:Message.Frame.points)
  return points_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Message_Frame_Point >*
Message_Frame::mutable_points() {
  // @@protoc_insertion_point(field_mutable_list:Message.Frame.points)
  return &points_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Message_Frame_Point >&
Message_Frame::points() const {
  // @@protoc_insertion_point(field_list:Message.Frame.points)
  return points_;
}

// float timestamp = 2;
inline void Message_Frame::clear_timestamp() {
  timestamp_ = 0;
}
inline float Message_Frame::timestamp() const {
  // @@protoc_insertion_point(field_get:Message.Frame.timestamp)
  return timestamp_;
}
inline void Message_Frame::set_timestamp(float value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:Message.Frame.timestamp)
}

// -------------------------------------------------------------------

// Message

// repeated .Message.Frame frames = 1;
inline int Message::frames_size() const {
  return frames_.size();
}
inline void Message::clear_frames() {
  frames_.Clear();
}
inline const ::Message_Frame& Message::frames(int index) const {
  // @@protoc_insertion_point(field_get:Message.frames)
  return frames_.Get(index);
}
inline ::Message_Frame* Message::mutable_frames(int index) {
  // @@protoc_insertion_point(field_mutable:Message.frames)
  return frames_.Mutable(index);
}
inline ::Message_Frame* Message::add_frames() {
  // @@protoc_insertion_point(field_add:Message.frames)
  return frames_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Message_Frame >*
Message::mutable_frames() {
  // @@protoc_insertion_point(field_mutable_list:Message.frames)
  return &frames_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Message_Frame >&
Message::frames() const {
  // @@protoc_insertion_point(field_list:Message.frames)
  return frames_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_message_2eproto__INCLUDED
