// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Message_Frame;
@class Message_Frame_Point;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MessageRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MessageRoot : GPBRootObject
@end

#pragma mark - Message

typedef GPB_ENUM(Message_FieldNumber) {
  Message_FieldNumber_FramesArray = 1,
};

@interface Message : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Message_Frame*> *framesArray;
/** The number of items in @c framesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger framesArray_Count;

@end

#pragma mark - Message_Frame

typedef GPB_ENUM(Message_Frame_FieldNumber) {
  Message_Frame_FieldNumber_PointsArray = 1,
  Message_Frame_FieldNumber_Timestamp = 2,
};

@interface Message_Frame : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Message_Frame_Point*> *pointsArray;
/** The number of items in @c pointsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger pointsArray_Count;

@property(nonatomic, readwrite) float timestamp;

@property(nonatomic, readwrite) BOOL hasTimestamp;
@end

#pragma mark - Message_Frame_Point

typedef GPB_ENUM(Message_Frame_Point_FieldNumber) {
  Message_Frame_Point_FieldNumber_X = 1,
  Message_Frame_Point_FieldNumber_Y = 2,
  Message_Frame_Point_FieldNumber_Z = 3,
  Message_Frame_Point_FieldNumber_R = 4,
  Message_Frame_Point_FieldNumber_G = 5,
  Message_Frame_Point_FieldNumber_B = 6,
};

@interface Message_Frame_Point : GPBMessage

@property(nonatomic, readwrite) float x;

@property(nonatomic, readwrite) BOOL hasX;
@property(nonatomic, readwrite) float y;

@property(nonatomic, readwrite) BOOL hasY;
@property(nonatomic, readwrite) float z;

@property(nonatomic, readwrite) BOOL hasZ;
@property(nonatomic, readwrite) float r;

@property(nonatomic, readwrite) BOOL hasR;
@property(nonatomic, readwrite) float g;

@property(nonatomic, readwrite) BOOL hasG;
@property(nonatomic, readwrite) float b;

@property(nonatomic, readwrite) BOOL hasB;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
